import { FilamentProduct, Order, SubscriptionPlan, MemberProfile, AnalyticsData } from './types';

export const INITIAL_PRODUCTS: FilamentProduct[] = [
  {
    id: 'prod-pla-hf-01',
    name: 'Hyper-Speed 高速 PLA+ 專業線材',
    brand: '神狗勾',
    material: 'High-Speed PLA',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 490,
    originalPrice: 650,
    stock: 142,
    sku: 'PC-HPLA-001',
    spoolType: 'Cardboard 環保紙盤',
    nozzleTemp: '200°C - 230°C',
    bedTemp: '50°C - 60°C',
    maxSpeed: '高達 600 mm/s (適配 Bambu / K1 / Prusa)',
    rating: 4.9,
    reviewsCount: 328,
    badge: '熱銷爆款 🔥',
    description: '專為次世代高速 3D 印表機研發，流動性提升 300%，高速擠出不卡料、層間黏合力極佳，表面霧面啞光細膩無層紋。',
    features: ['適配 600mm/s 高速列印', '耐衝擊強度提高 40%', '環保可生物分解無毒配方', 'RFID/線盤相容 AMS 多色系統'],
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: true,
    colors: [
      { name: '消光黑 (Matte Black)', hex: '#1e293b', stock: 45 },
      { name: '極光白 (Arctic White)', hex: '#f8fafc', stock: 38 },
      { name: '太空灰 (Space Grey)', hex: '#64748b', stock: 26 },
      { name: '軍規綠 (Tactical Green)', hex: '#3f6212', stock: 18 },
      { name: '法拉利紅 (Racing Red)', hex: '#dc2626', stock: 15 },
    ]
  },
  {
    id: 'prod-petg-hf-02',
    name: 'PETG-HF 高速耐候耐溫線材',
    brand: '神狗勾',
    material: 'PETG',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 520,
    originalPrice: 680,
    stock: 89,
    sku: 'PC-PETG-002',
    spoolType: 'High-Temp Reusable 耐高溫線盤',
    nozzleTemp: '230°C - 255°C',
    bedTemp: '70°C - 80°C',
    maxSpeed: '300 mm/s',
    rating: 4.8,
    reviewsCount: 194,
    badge: '戶外耐候首選',
    description: '結合 PLA 的易印性與 ABS 的結構強度，優異的抗 UV 與防潮耐酸鹼特性，非常適合戶外無人機支架與車用配件。',
    features: ['抗拉強度 52 MPa', '熱變形溫度 75°C', '極低收縮無翹曲', '超低牽絲配方'],
    imageUrl: 'https://images.unsplash.com/photo-1615915468538-0fbd857888ca?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: true,
    colors: [
      { name: '碳墨黑 (Carbon Black)', hex: '#111827', stock: 32 },
      { name: '半透明冰晶 (Translucent Ice)', hex: '#e0f2fe', stock: 24 },
      { name: '高光皇家藍 (Royal Blue)', hex: '#1d4ed8', stock: 19 },
      { name: '活力橙 (Safety Orange)', hex: '#ea580c', stock: 14 },
    ]
  },
  {
    id: 'prod-pla-cf-03',
    name: 'PLA-CF 航太級碳纖維複合耗材',
    brand: 'AeroForge 3D',
    material: 'Carbon Fiber',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 880,
    originalPrice: 1150,
    stock: 46,
    sku: 'PC-CFPLA-003',
    spoolType: 'High-Temp Reusable 耐高溫線盤',
    nozzleTemp: '215°C - 240°C',
    bedTemp: '55°C - 65°C',
    maxSpeed: '250 mm/s',
    rating: 5.0,
    reviewsCount: 156,
    badge: '工程級首選 ⭐',
    description: '添加 15% 高模量短切碳纖維，剛性與彎曲模量提升 210%，呈現奢華消光黑質地，徹底隱形層紋。需搭配硬化鋼噴嘴。',
    features: ['添加 15% 短切碳纖維', '絕佳結構剛性與尺寸精度', '消光紋理隱形分層', '低磨耗順暢出料'],
    imageUrl: 'https://images.unsplash.com/photo-1633493752646-665a31a9fd63?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: true,
    colors: [
      { name: '曜石碳纖黑 (Carbon Stealth)', hex: '#18181b', stock: 28 },
      { name: '星艦鈦灰 (Titanium Grey)', hex: '#475569', stock: 18 },
    ]
  },
  {
    id: 'prod-tpu-95a-04',
    name: 'TPU 95A 高彈性耐磨軟膠線材',
    brand: 'FlexCraft',
    material: 'TPU',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 650,
    originalPrice: 790,
    stock: 52,
    sku: 'PC-TPU-004',
    spoolType: 'Cardboard 環保紙盤',
    nozzleTemp: '210°C - 230°C',
    bedTemp: '30°C - 50°C',
    maxSpeed: '80 - 150 mm/s',
    rating: 4.7,
    reviewsCount: 112,
    badge: '柔性抗震',
    description: '蕭氏硬度 95A，斷裂伸長率高達 450%，具備優異耐油耐磨性。適合手機殼、緩衝腳墊、密封圈、仿生關節列印。',
    features: ['斷裂伸長率 450%', '抗衝擊減震絕佳', '耐磨損與化學耐受性', '改進配方不卡喉管'],
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: true,
    colors: [
      { name: '經典啞黑 (Matte Black)', hex: '#09090b', stock: 22 },
      { name: '晶透螢光綠 (Neon Green)', hex: '#4ade80', stock: 16 },
      { name: '珊瑚粉紅 (Coral Pink)', hex: '#f43f5e', stock: 14 },
    ]
  },
  {
    id: 'prod-abs-pro-05',
    name: 'ABS+ 航模耐衝擊改性線材 (低氣味)',
    brand: '神狗勾',
    material: 'ABS',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 540,
    originalPrice: 690,
    stock: 63,
    sku: 'PC-ABS-005',
    spoolType: 'High-Temp Reusable 耐高溫線盤',
    nozzleTemp: '245°C - 265°C',
    bedTemp: '90°C - 105°C',
    maxSpeed: '250 mm/s',
    rating: 4.6,
    reviewsCount: 88,
    badge: '耐熱 100°C',
    description: '採用低揮發性單體聚合改性，大幅降低列印氣味與收縮翹曲率。具備 100°C 耐溫與可丙酮蒸氣拋光特性。建議於封閉機箱列印。',
    features: ['熱變形溫度 98°C', '可丙酮化學平滑表面', '高抗衝擊韌性', '低氣味低VOC配方'],
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: false,
    colors: [
      { name: '工業純黑 (Industrial Black)', hex: '#18181b', stock: 35 },
      { name: '純潔白 (Clean White)', hex: '#ffffff', stock: 28 },
    ]
  },
  {
    id: 'prod-resin-8k-06',
    name: '8K 高精細光固化標準樹脂 (低氣味高韌性)',
    brand: 'ResinWorks',
    material: 'Resin',
    diameter: '1.75mm',
    weight: '1.0kg',
    price: 750,
    originalPrice: 950,
    stock: 41,
    sku: 'RW-8KR-006',
    spoolType: 'Refill 裸裝補充包',
    nozzleTemp: '25°C - 30°C (環境)',
    bedTemp: 'N/A',
    maxSpeed: '曝光時間 1.8s / 層',
    rating: 4.9,
    reviewsCount: 142,
    badge: '手辦模型專用',
    description: '專為 4K/8K/12K LCD 與 DLP 光固化印表機調配，收縮率小於 3.5%，顯現驚人的微米級頭髮與皮膚細節，低氣味好清洗。',
    features: ['極低體積收縮率 (<3.5%)', '高解析度表面微紋理', '低黏度流動快速', '易酒精清洗不發脆'],
    imageUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: true,
    colors: [
      { name: '太空灰 (Model Grey)', hex: '#6b7280', stock: 25 },
      { name: '陶瓷白 (Ceramic White)', hex: '#f3f4f6', stock: 16 },
    ]
  },
  {
    id: 'prod-acc-nozzle-07',
    name: 'Bambu / Prusa 專用硬化鋼高流量 CHT 噴嘴套組 (0.4 / 0.6mm)',
    brand: '神狗勾',
    material: 'Accessories',
    diameter: '1.75mm',
    weight: '0.5kg',
    price: 399,
    originalPrice: 550,
    stock: 95,
    sku: 'ACC-CHT-007',
    spoolType: 'Cardboard 環保紙盤',
    nozzleTemp: '最高 500°C',
    bedTemp: 'N/A',
    maxSpeed: '熔融流量 +45%',
    rating: 4.9,
    reviewsCount: 215,
    badge: '耗材神配件',
    description: '三孔分流 CHT 專利設計，體積熔融流量提升 45%，搭配 55HRC 淬火硬化鋼外殼，終生耐磨抗碳纖與玻纖耗材磨損。',
    features: ['三孔高流量快速融化', '55 HRC 硬化鋼耐磨塗層', '防漏膠精密螺牙', '支援 0.4mm / 0.6mm 替換'],
    imageUrl: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: false,
    colors: [
      { name: '槍黑硬化鋼 (Gunmetal Steel)', hex: '#374151', stock: 95 }
    ]
  },
  {
    id: 'prod-acc-drybox-08',
    name: 'SmartDry 恆溫加熱循環耗材防潮烘乾盒 (帶即時秤重)',
    brand: 'DryTech 3D',
    material: 'Accessories',
    diameter: '1.75mm',
    weight: '2.5kg',
    price: 1390,
    originalPrice: 1800,
    stock: 28,
    sku: 'ACC-DRY-008',
    spoolType: 'High-Temp Reusable 耐高溫線盤',
    nozzleTemp: '加熱 40°C - 70°C',
    bedTemp: 'N/A',
    maxSpeed: '即時除濕邊印邊烘',
    rating: 5.0,
    reviewsCount: 89,
    badge: '雨天救星 ☔',
    description: '360° 熱風環繞立體循環，可容納 1kg 線盤，內建高精度濕度感應器與剩餘線材重量即時數顯，支援邊烘烤邊進料列印。',
    features: ['最高 70°C 支援高階工程料', '剩餘耗材克數即時秤重', '超靜音 PTC 陶瓷加熱風扇', '防逆轉專利鐵氟龍出線口'],
    imageUrl: 'https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?auto=format&fit=crop&w=600&q=80',
    isSubscriptionEligible: false,
    colors: [
      { name: '極簡曜石黑 (Onyx Black)', hex: '#111827', stock: 28 }
    ]
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'TW-20260906-8921',
    createdAt: '2026-09-06 08:32',
    customerName: '陳冠宇',
    customerEmail: 'kuanyu.chen@maker.tw',
    customerPhone: '0912-345-678',
    shippingMethod: '7-11',
    storeOrAddress: '7-11 敦南科技門市 (店號 992813)',
    items: [
      {
        productId: 'prod-pla-hf-01',
        name: 'Hyper-Speed 高速 PLA+ 專業線材',
        colorName: '消光黑 (Matte Black)',
        colorHex: '#1e293b',
        price: 490,
        quantity: 2
      },
      {
        productId: 'prod-pla-cf-03',
        name: 'PLA-CF 航太級碳纖維複合耗材',
        colorName: '曜石碳纖黑 (Carbon Stealth)',
        colorHex: '#18181b',
        price: 880,
        quantity: 1
      }
    ],
    subtotal: 1860,
    shippingFee: 0,
    discount: 100,
    pointsDeduction: 50,
    pointsEarned: 171,
    total: 1710,
    paymentGateway: 'ecpay_credit',
    paymentStatus: 'paid',
    orderStatus: 'in_transit',
    trackingNumber: '71192841028',
    invoiceNumber: 'TW-202609-84729103',
    invoiceType: 'mobile_barcode',
    invoiceCarrierValue: '/AB12345',
    notes: '請幫我包裝加固防震，謝謝！'
  },
  {
    id: 'ord-1002',
    orderNumber: 'TW-20260906-8922',
    createdAt: '2026-09-06 09:10',
    customerName: '林雅婷 (Maker Space)',
    customerEmail: 'yating.lin@techfab.org',
    customerPhone: '0928-765-432',
    shippingMethod: 'blackcat',
    storeOrAddress: '台北市南港區軟體園區二期三重路66號5樓',
    items: [
      {
        productId: 'prod-petg-hf-02',
        name: 'PETG-HF 高速耐候耐溫線材',
        colorName: '碳墨黑 (Carbon Black)',
        colorHex: '#111827',
        price: 520,
        quantity: 3
      },
      {
        productId: 'prod-acc-drybox-08',
        name: 'SmartDry 恆溫加熱循環耗材防潮烘乾盒',
        colorName: '極簡曜石黑 (Onyx Black)',
        colorHex: '#111827',
        price: 1390,
        quantity: 1
      }
    ],
    subtotal: 2950,
    shippingFee: 0,
    discount: 150,
    pointsDeduction: 0,
    pointsEarned: 280,
    total: 2800,
    paymentGateway: 'linepay',
    paymentStatus: 'paid',
    orderStatus: 'picking',
    trackingNumber: '90218492019',
    invoiceNumber: 'TW-202609-84729104',
    invoiceType: 'tax_id',
    invoiceCarrierValue: '83921049 (創客科技股份)',
    notes: '急件，下午送達請打手機聯絡'
  },
  {
    id: 'ord-1003',
    orderNumber: 'TW-20260906-8923',
    createdAt: '2026-09-06 09:15',
    customerName: '張哲銘',
    customerEmail: 'jeremy.chang@gmail.com',
    customerPhone: '0933-112-233',
    shippingMethod: 'familymart',
    storeOrAddress: '全家 龍潭大池店 (服務代碼 019284)',
    items: [
      {
        productId: 'prod-tpu-95a-04',
        name: 'TPU 95A 高彈性耐磨軟膠線材',
        colorName: '晶透螢光綠 (Neon Green)',
        colorHex: '#4ade80',
        price: 650,
        quantity: 1
      }
    ],
    subtotal: 650,
    shippingFee: 60,
    discount: 0,
    pointsDeduction: 30,
    pointsEarned: 68,
    total: 680,
    paymentGateway: 'ecpay_cvs',
    paymentStatus: 'paid',
    orderStatus: 'new',
    trackingNumber: 'FM9910293810',
    invoiceNumber: 'TW-202609-84729105',
    invoiceType: 'cloud'
  }
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'sub-maker-box',
    name: '創客嚐鮮月配盒 (Maker Starter)',
    badge: '新手首選',
    pricePerMonth: 899,
    spoolsCount: 2,
    frequency: '每月',
    description: '每月精選 2 卷當季熱門 High-Speed PLA+ 或 PETG，隨盒贈送客製化 3D 列印樣品與限定貼紙。',
    perks: [
      '享官網商品全年度 88 折優惠',
      '全台 7-11 / 全家 免運送到店',
      '每月自選或盲盒隨機驚喜色',
      '贈限定 STL 創客模型檔下載碼'
    ],
    recommendedFor: '個人玩家、週末創客、學生工作室'
  },
  {
    id: 'sub-pro-box',
    name: '工程專家旗艦盒 (Pro Engineer Box)',
    badge: '熱門訂閱 🔥',
    pricePerMonth: 1980,
    spoolsCount: 4,
    frequency: '每月',
    description: '專業工作室專屬！每月 4 卷高階工程耗材（含 PLA-CF 碳纖維、PETG、ABS+ 或 TPU），附贈硬化鋼耐磨噴嘴。',
    perks: [
      '享全站現折 8 折 VIP 特權',
      '宅配免運 + 優先排單極速出貨',
      '每季加贈 1 支高流量 CHT 硬化鋼噴嘴',
      '一對一專屬工程師切片參數除錯顧問'
    ],
    recommendedFor: '小型打樣代工廠、產品設計公司、極客發燒友'
  },
  {
    id: 'sub-color-box',
    name: '多色宇宙狂熱盒 (AMS Multi-Color Club)',
    badge: '多色必備 🎨',
    pricePerMonth: 1550,
    spoolsCount: 4,
    frequency: '每月',
    description: '專為 Bambu Lab AMS、Anycubic ACE、Prusa MMU 多色系統量身打造，每月精準配比 4 卷高階同調特色耗材。',
    perks: [
      '色盤絕不重複，搶先體驗全新未上市限定色',
      '附 RFID 自動感應標籤 (相容多色機)',
      '全年度耗材配件 85 折',
      '專屬創客社群交流與多色模型切片包'
    ],
    recommendedFor: '多色印表機愛好者、模型塗裝愛好者、潮玩公仔創作者'
  }
];

export const DEFAULT_MEMBER: MemberProfile = {
  id: 'usr-vip-99',
  name: '王小明 (Ming Maker)',
  email: 'babe0615@gmail.com',
  phone: '0912-345-678',
  tier: 'Gold',
  points: 480,
  totalSpent: 18450,
  ordersCount: 9,
  referralCode: 'MING3D',
  birthday: '1995-06-15'
};

export const INITIAL_ANALYTICS: AnalyticsData = {
  visitorsToday: 4280,
  pageViewsToday: 18920,
  addToCartCount: 684,
  checkoutStarts: 246,
  ordersCompleted: 158,
  conversionRate: 3.69,
  revenueToday: 124800,
  bounceRate: 26.8,
  avgOrderValue: 790,
  googleAdsRoas: 5.2,
  googleAdsSpent: 18200,
  googleAdsClicks: 1640,
  hourlyVisits: [
    { hour: '00:00', visits: 85, orders: 3 },
    { hour: '03:00', visits: 42, orders: 1 },
    { hour: '06:00', visits: 110, orders: 4 },
    { hour: '09:00', visits: 380, orders: 16 },
    { hour: '12:00', visits: 620, orders: 28 },
    { hour: '15:00', visits: 740, orders: 34 },
    { hour: '18:00', visits: 910, orders: 42 },
    { hour: '21:00', visits: 1120, orders: 52 },
    { hour: '23:00', visits: 273, orders: 12 },
  ],
  trafficSources: [
    { name: 'Google Ads (搜尋/購物)', percentage: 48, color: '#3b82f6', visits: 2054, cvr: 4.8 },
    { name: 'Google 自然搜尋 (SEO)', percentage: 24, color: '#10b981', visits: 1027, cvr: 3.4 },
    { name: 'LINE 官方帳號/推播', percentage: 16, color: '#06c755', visits: 685, cvr: 6.2 },
    { name: '社群推薦 (Facebook/IG)', percentage: 8, color: '#f59e0b', visits: 342, cvr: 2.1 },
    { name: '直接造訪 (Direct)', percentage: 4, color: '#8b5cf6', visits: 172, cvr: 4.1 },
  ],
  topCampaigns: [
    {
      campaignName: 'TW_Search_HighSpeed_PLA [高速耗材]',
      channel: 'Google Search',
      spent: 6500,
      revenue: 38400,
      roas: 5.9,
      cvr: 5.1
    },
    {
      campaignName: 'TW_Shopping_CarbonFiber_PETG [工程級耗材]',
      channel: 'Google Shopping',
      spent: 5800,
      revenue: 31900,
      roas: 5.5,
      cvr: 4.6
    },
    {
      campaignName: 'TW_LINEPay_100Coupon [LINE Pay 限定滿千折百]',
      channel: 'LINE Official',
      spent: 3200,
      revenue: 22400,
      roas: 7.0,
      cvr: 6.8
    },
    {
      campaignName: 'TW_Dynamic_Remarketing_CartAbandon [購物車挽回動態廣告]',
      channel: 'Meta Dynamic',
      spent: 2700,
      revenue: 13200,
      roas: 4.88,
      cvr: 4.2
    }
  ]
};
